### PR TITLE
Added truck backer upper

### PR DESCRIPTION
**Pull request by TiFu**
Should I change the screenshot? It's a bit smaller than the other ones:
a

### CODE REVIEW

**Comment by phiresky** [comment]
yeah would be good if it was the same format as the other screenshots, especially because it kills the layout if it was farther up

**Comment by phiresky** [comment]
also, the remote url should be the https url otherwise it can't be cloned without login data (and i think github pages will also refuse it)

**Comment by TiFu** [comment]
Alright. Will fix that later

**Comment by TiFu** [comment]
Done

**Pull request merged**
